# Generated by Django 4.1.7 on 2023-02-18 11:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='название курса')),
                ('image', models.ImageField(blank=True, null=True, upload_to='skypro/', verbose_name='картинка для курсов')),
                ('description', models.TextField(blank=True, null=True, verbose_name='описание курса')),
            ],
            options={
                'verbose_name': 'курс',
                'verbose_name_plural': 'курсы',
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='название урока')),
                ('description', models.TextField(blank=True, null=True, verbose_name='описание урока')),
                ('image', models.ImageField(blank=True, null=True, upload_to='skypro/', verbose_name='картинка для урока')),
                ('link_video', models.FileField(blank=True, null=True, upload_to='skypro/', verbose_name='видео')),
                ('course_title', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='skypro.course', verbose_name='урок из курса')),
            ],
            options={
                'verbose_name': 'урок',
                'verbose_name_plural': 'уроки',
            },
        ),
    ]
