# Generated by Django 4.1.7 on 2023-03-01 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skypro', '0004_subscription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='link_video',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='видео'),
        ),
    ]
