# Generated by Django 4.1.7 on 2023-03-04 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skypro', '0005_alter_lesson_link_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='price',
            field=models.FloatField(blank=True, null=True, verbose_name='цена курса'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='price',
            field=models.FloatField(blank=True, null=True, verbose_name='цена урока'),
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_log',
            field=models.JSONField(blank=True, null=True, verbose_name='ответ на пост запрос'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'наличные'), ('card', 'банковская карта')], default='card', max_length=50, verbose_name='способ оплаты'),
        ),
    ]
