# Generated by Django 4.1.7 on 2023-03-04 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skypro', '0006_course_price_lesson_price_payment_payment_log_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_amount',
            field=models.FloatField(blank=True, null=True, verbose_name='сумма оплаты'),
        ),
    ]
