# Generated by Django 4.1.7 on 2023-03-06 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skypro', '0008_alter_payment_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Success', models.BooleanField(default=False)),
                ('ErrorCode', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('TerminalKey', models.CharField(blank=True, max_length=100, null=True)),
                ('Status', models.CharField(blank=True, max_length=50, null=True)),
                ('PaymentId', models.CharField(blank=True, max_length=100, null=True)),
                ('OrderId', models.CharField(blank=True, max_length=100, null=True)),
                ('Amount', models.PositiveBigIntegerField(blank=True, default=0, null=True)),
                ('PaymentURL', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='payment',
            name='payment_log',
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_amount',
            field=models.FloatField(default=0, verbose_name='сумма оплаты'),
        ),
    ]
